<?php 
return [
'cnf_appname' 			=> 'ZRF Quiz 2021',
'cnf_appdesc' 			=> 'ZRF Quiz Olympiad',
'cnf_comname' 			=> 'Ziaur Rahman Foundation',
'cnf_email' 			=> 'info@ziaurrahmanfoundation.org',
'cnf_metakey' 			=> 'B2B Solver',
'cnf_metadesc' 		=> 'Write description for your site',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'manual',
'cnf_multilang' 		=> '0',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'true',
'cnf_front' 			=> 'false',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'default',
'cnf_backend' 			=> 'minimal',
'cnf_recaptchapublickey' => '',
'cnf_recaptchaprivatekey' => '',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'backend-logo.png',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21',
'cnf_mail' 			=> 'swift',
'cnf_maps' 			=> '',
'cnf_date' 			=> 'Y-m-d',
];
